### ISSUE TITLE
Creating a document from non-empty folder

### ISSUE THREAD

**Issue by monvoisinf** [decima/kip#37]
As it is, one can only create a document from an empty folder.

- enable to create new documents from non-empty folders too.
- add a proposition to create a readme when we click on a folder which has no readme (right now it just says that the document "title of the folder" couldn't be found and propose to create a new document, without mentioning a readme

**Comment by decima** [comment]
Afaik you can create a file in a non-empty folder by going on the URL
/path/to/folder/myfile.md

If you go on /path/to/folder/myfile, it will try to create a
/path/to/folder/myfile/readme.md

This is the current decided behavior

Le mar. 14 avr. 2020 à 13:58, monvoisinf <notifications@github.com> a
écrit :
