### ISSUE TITLE
Better UI for the editor

### ISSUE THREAD

**Issue by monvoisinf** [decima/kip#41]
The editor isn't enough, an editor like HackMD would be better, especially for the previsualization tool.

**Comment by DamienDabernat** [comment]
Maybe a dark theme ?

<img width="565" alt="Capture d’écran 2020-04-14 à 16 34 45" src="https://user-images.githubusercontent.com/10465660/79237298-49548680-7e6e-11ea-961c-7a66d1c8d1fe.png">

**Comment by decima** [comment]
I used this lib : https://simplemde.com/ witch can be customized
