### ISSUE TITLE
CSS / UI rework

### ISSUE THREAD

**Issue by monvoisinf** [decima/kip#42]
This needs to be done after the issue #34 : it also needs conception so don't hesitate to suggest different things.

**Comment by monvoisinf** [comment]
A few suggestions for the right minimap :
 - change the padding of the right minimap (both right and left) as it is too close to the text and too close to the border of the screen
 - it needs, when we scroll down, to go up (it is in the middle of the screen because of the title with a black background on top of the document, but when we scroll down, currently it stays on the middle of the screen, which is weird)
 - maybe add a background color for it, to make a clear distinction with the content of the document ?

**Comment by AlbanCrepel** [comment]
Here is a prototype for the new UI designed in Figma : [https://www.figma.com/file/K4MTfRurkq3Rem84NVZQv6/KIP?node-id=0%3A1](https://www.figma.com/file/K4MTfRurkq3Rem84NVZQv6/KIP?node-id=0%3A1)
