### ISSUE TITLE
tui.editor as replacement of SimpleMDE

### ISSUE THREAD

**Issue by decima** [decima/kip#56]
[Tui.editor](https://github.com/nhn/tui.editor) offers a good alternative to SimpleMDE, it is quite better for image upload, table handling and other cool features.

+ : there is a [vue component](https://github.com/nhn/tui.editor/tree/master/apps/vue-editor) for it.

What do you all think?

**Comment by AlbanCrepel** [comment]
Yes it seems better ! As I will work on the project this Friday, I might implement it.
